spring:
  profiles:
    active: ${ACTIVE_PROFILE:dev}

  datasource:
    url: jdbc:mysql://${MySQL_HOST}:${MySQL_PORT}/${MySQL_DB}?createDatabaseIfNotExist=true
    password: ${MySQL_PASSWORD:}
    username: ${MySQL_USERNAME:root}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers : true
        globally_quoted_identifiers_skip_column_definitions : true
        format_sql: true
#logging:
#  level:
#    org.springframework.data.jpa.repository.query: DEBUG
#    org.hibernate: DEBUG

